from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / ".neurotrace_work"


def card(key, page, quote, interpretation, role, rationale, question, sample,
         metrics, region, window, comparison, result, limits, demos):
    return {
        "zotero_item_key": key,
        "pdf_page": page,
        "original_quote": quote,
        "chinese_interpretation": interpretation,
        "evidence_role": role,
        "role_rationale": rationale,
        "status": "candidate",
        "verification_flag": "page_located" if page else "needs_manual_check",
        "research_question_and_paradigm": question,
        "participants_and_sample_size": sample,
        "eeg_erp_metrics": metrics,
        "electrode_region": region,
        "time_window": window,
        "condition_comparison": comparison,
        "main_emotion_valence_arousal_result": result,
        "limitations_boundary_confounds": limits,
        "demo_question_ids": demos,
    }


BATCH_1 = [
    card(
        "WRJA7MMA", 1,
        "Emotional metaphors elicited a more positive LP (450–850 ms) than emotional literal sentences.",
        "在被动阅读任务中，情绪隐喻相较情绪字面句诱发更正的晚期正波。",
        "conditional_support",
        "直接观察到晚期正波差异，但方向依赖任务；同一论文的意义判断任务出现 N400 和晚期负波。",
        "两个实验比较情绪/中性、隐喻/字面句；实验1做意义判断，实验2被动阅读并偶尔回答理解题。",
        "实验1：39名英语母语本科生，排除6名后 n=33；实验2：36名，排除4名后 n=32。",
        ["N400", "LP", "LN"],
        "前/后 × 左/右四象限；实验1晚期效应偏左前，实验2 N400 小效应偏右后。",
        "N400 300–450 ms；LP/LN 450–850 ms。",
        "情绪隐喻 vs 情绪字面句，并与中性条件和任务类型交叉比较。",
        "情绪性与隐喻性的联合作用随任务要求改变：主动判断出现 N400/LN，被动阅读出现 LP。",
        "不能把 LP 方向推广到所有任务；刺激情绪性与隐喻性共同变化，任务注意目标是关键混淆/边界。",
        ["Q1", "Q2"],
    ),
    card(
        "8XBDTNCB", 10,
        "L2 participants with higher emotional resonance capabilities showed a larger LPC congruency effect overall.",
        "L2 使用者的情绪共鸣能力越高，总体 LPC 情绪一致性效应越大。",
        "conditional_support",
        "情绪共鸣作为个体差异调节 LPC，但材料是新学伪词且任务为情绪一致性判断。",
        "将中文伪词与厌恶/悲伤面孔配对学习，次日判断句子与伪词的情绪一致性。",
        "23名中文母语者与20名中文二语者，总 n=43。",
        ["N400", "LPC"],
        "混合效应模型跨所选通道；具体 ROI 需人工复核方法表。",
        "N400 250–430 ms；LPC 450–700 ms。",
        "情绪一致 vs 不一致；厌恶 vs 悲伤；L1 vs L2；L2 情绪共鸣连续变量。",
        "不一致试次产生更大 N400/LPC；L2 情绪共鸣更强者 LPC 一致性效应更大，N400 调节还依赖情绪类别。",
        "伪词快速学习、仅两类负性情绪、文化匹配的面孔与量表可能影响结果；不能等同一般情绪波动。",
        ["Q1", "Q2", "Q3"],
    ),
    card(
        "FM494I2T", 1,
        "We found greater LPP amplitude to emotionally salient compared to neutral stimuli.",
        "情绪显著图片相较中性图片诱发更大的 LPP。",
        "direct_support",
        "在图片任务中直接比较情绪显著与中性刺激并观察 LPP 振幅差异。",
        "老年人观看不愉快/中性图片，随后自然反应或认知重评；同时记录主观负性情绪。",
        "原始 n=47（60–84岁）；LPP 分析 n=46；高/低情绪幸福感分组。",
        ["LPP"],
        "LPP 计分区域需人工复核方法表。",
        "指令前与指令后 LPP；精确毫秒窗需人工复核。",
        "情绪显著 vs 中性；自然反应 vs 重评；高 vs 低幸福感。",
        "情绪显著刺激 LPP 更大，重评后 LPP 下降；较高抑郁症状者总体 LPP 更钝化。",
        "仅老年社区样本；分组未显示 LPP 调节能力差异；实际采用的调节策略未被完整记录。",
        ["Q1", "Q3"],
    ),
    card(
        "5PICEPUM", 1,
        "The results provide preliminary evidence that the LPP reflects a global inhibition of activity in visual cortex.",
        "结果初步支持：LPP 可能反映视觉皮层活动的全局抑制，而非单一的情绪强度读数。",
        "boundary",
        "论文讨论 LPP 的功能机制，并明确使用 preliminary evidence；它限制了把 LPP 直接解释为情绪本身的做法。",
        "两个实验用负性/中性 IAPS 图片调节 LPP，再用 Gabor 知觉和 P1/N1 探测后续视觉处理。",
        "实验2为25名健康青年；实验1样本量未在当前锚点中定位。",
        ["LPP", "P1", "N1"],
        "视觉后部为主；精确电极集合需人工复核。",
        "LPP 主要约 400–600 ms，可延续至刺激后约1秒；P1/N1 为后续探针反应。",
        "负性 vs 中性图片；不同刺激间隔；后续非情绪视觉探针。",
        "较大 LPP 与后续视觉反应下降的模式相符，但作者只称为初步证据。",
        "短时呈现、视觉图片范式与语言 LPC 不同；相关/间接机制证据不等于 LPP 的唯一功能。",
        ["Q1"],
    ),
    card(
        "PFPR5ENP", 1,
        "Significance is related to emotional properties, but also to individual differences, task demands, context, and other factors.",
        "LPP 所反映的显著性既受情绪属性影响，也受个体差异、任务、语境等因素调节。",
        "boundary",
        "综述直接指出多重决定因素，反对把 LPP 振幅单独当作唤醒度或情绪波动的普适指标。",
        "理论综述：用 P300 的情境更新框架讨论情绪相关 LPP、记忆和重评。",
        "综述，不适用单一样本量。",
        ["P300", "LPP"],
        "跨研究；典型后部到中央正波分布。",
        "跨研究时间窗不一；文中讨论早期/持续 LPP。",
        "综合情绪/中性、记忆、重评、任务相关性与个体差异研究。",
        "LPP 与情绪显著性稳定相关，但其功能可由情境更新、记忆和意义评价共同解释。",
        "理论整合而非单一实验；LPP 与 P300 的区分、任务定义和记忆结果仍需逐研究限定。",
        ["Q1", "Q3"],
    ),
    card(
        "9473VCG3", 4,
        "ERP research revealed inconsistent results ... due to ... little control of the experimental material [and] peculiar designs.",
        "情绪词 ERP 研究的结果不一致，部分来自材料控制不足和实验设计差异。",
        "boundary",
        "该综述把跨研究不一致归因于方法差异，直接限制了对效价/唤醒度效应的强综合。",
        "综述书面情绪词的 ERP 与 fMRI 研究，重点区分效价、唤醒度及二者交互。",
        "综述，不适用单一样本量。",
        ["P2", "EPN", "N400", "LPC"],
        "跨研究，常见后部 EPN 与中央/后部 LPC，但分布不统一。",
        "跨研究约 180–800 ms，具体窗随任务而变。",
        "正/负/中性词，效价与唤醒度正交或非正交；词汇判断、情绪 Stroop、语义任务等。",
        "效价与唤醒度可独立或交互影响多个成分，但方向和出现时间受任务与材料控制影响。",
        "综述含 ERP 与 fMRI，研究设计异质；词频、熟悉度、具体性、自我相关和个体评分均可能混淆。",
        ["Q1", "Q2", "Q3"],
    ),
    card(
        "ATKC5SQC", 6,
        "Emotional influences on the LPP relate to the emotional intensity of stimuli.",
        "综述认为，LPP 的情绪调节与刺激的情绪强度有关。",
        "conditional_support",
        "支持 LPP 与情绪强度/动机显著性相关，但同段明确排除把效应简单归因于新奇或低级视觉特征。",
        "整合性综述，涵盖情绪图片、P300/LPP、注意及情绪调节。",
        "综述，不适用单一样本量。",
        ["P300", "LPP", "temporospatial PCA"],
        "P300 常见枕顶约350 ms；PCA 分离出的 LPP 为枕部至中央，峰约850与1600 ms。",
        "跨研究；包含早期 P300 与持续 LPP。",
        "情绪 vs 中性图片；注意/评价任务；重评、抑制等调节条件。",
        "情绪强度和动机显著性通常增强 LPP，注意方式与评价也会改变振幅。",
        "综述中的成分命名与时间窗并不统一；P300、LPP 需通过时空 PCA 或设计加以区分。",
        ["Q1", "Q3"],
    ),
    card(
        "9PIPX6I5", 1,
        "We synthesized findings from 22 studies (N = 627) examining N400 and/or LPC/P600 ERP responses.",
        "该元分析汇总了22项研究、627名参与者的 N400 与 LPC/P600 结果。",
        "conditional_support",
        "提供跨研究量化证据，但聚焦隐喻常规性而非情绪变量，只能约束 N400/LPC 的机制解释。",
        "元分析比较隐喻与字面表达，以及新颖与常规隐喻的 N400/LPC。",
        "22项研究，总 N=627，主要为健康青年/大学生。",
        ["N400", "LPC", "P600"],
        "跨研究，ROI 与成分定义不一致。",
        "N400 多在350–500 ms；LPC/P600 窗跨研究变化。",
        "隐喻 vs 字面；新颖 vs 常规隐喻；常规性评分方法为调节变量。",
        "总体上隐喻较字面引出更负 N400 与较不正 LPC；晚期结果仍有异质性。",
        "晚期持续负波可能被误标为 LPC/P600；样本量和研究功效有限，群体主要是青年。",
        ["Q2", "Q3"],
    ),
    card(
        "ZL2RBLSC", 1,
        "Novel metaphors elicited smaller N400 and greater LPC amplitudes when participants had explained their meaning.",
        "参与者先解释新颖隐喻含义后，再次加工时 N400 较小、LPC 较大。",
        "boundary",
        "证明 N400/LPC 会被先前解释与学习经历改变，因此成分差异不能只归因于刺激固有属性。",
        "两词表达意义判断；比较先前解释含义与仅做快速意义判断后的重复加工。",
        "28名希伯来语母语者（12男、16女，平均23岁），均为右利手。",
        ["N400", "LPC"],
        "具体 ROI 需人工复核；文章报告整体 ERP 振幅变化。",
        "N400 与后续 LPC；精确毫秒窗需人工复核。",
        "字面、常规隐喻、新颖隐喻、无关词；先解释 vs 仅快速判断。",
        "对新颖隐喻的主动解释降低后续 N400 并提高 LPC；单纯重复判断没有同样效果。",
        "效应来自学习/解释操作和重复暴露；不涉及情绪操纵，不能直接支持情绪因果。",
        ["Q2", "Q3"],
    ),
]

BATCH_2 = [
    card(
        "8HE4L22P", 1,
        "The N400 [is] an event-related brain potential response linked to meaning processing.",
        "N400 是与意义加工相关的事件相关电位反应。",
        "boundary",
        "奠定 N400 的广义语义功能边界，防止把 N400 变化专门解释为情绪效应。",
        "叙述性综述，回顾 N400 的发现、诱发刺激、语义记忆与上下文机制。",
        "综述，不适用单一样本量。",
        ["N400"],
        "通常中央-顶区最明显，但分布随刺激和参照而变。",
        "典型峰约400 ms；振幅比潜伏期更常受操纵。",
        "跨文字、言语、手语、图片、面孔、动作、声音等多类刺激和语境。",
        "N400 对上下文、预期和语义记忆敏感，并非情绪或冲突专属指标。",
        "综述覆盖面广但非情绪专门研究；任何情绪解释都要排除可预测性、词汇与语义关联。",
        ["Q2", "Q3"],
    ),
    card(
        "PBD8NAYC", 2,
        "Metaphorical statements elicited more activity in the amygdala and anterior hippocampus than literal statements.",
        "隐喻句相较字面句引起更强的杏仁核和前海马活动。",
        "boundary",
        "支持隐喻更具情绪参与，但证据来自 fMRI，不能直接推断 N400/LPC 时间进程。",
        "fMRI 比较味觉源域隐喻句与匹配的字面释义，并控制熟悉度、意象性、效价和唤醒度。",
        "主实验样本量需人工复核；另有 n=34 的规范化评分样本。",
        ["fMRI BOLD"],
        "杏仁核、前海马；味觉相关词另见眶额皮层/额盖。",
        "不适用 ERP 时间窗。",
        "常规味觉隐喻 vs 字面释义；词级味觉对照。",
        "在效价/唤醒度匹配后，隐喻仍显示更强边缘系统活动。",
        "跨模态推断边界：BOLD 活动不能当作 N400/LPC 证据；隐喻限定为味觉源域。",
        ["Q2"],
    ),
    card(
        "GYCYN7VH", 1,
        "ERP analyses showed no effect of pain at an early-stage processing (N400).",
        "在该情感启动范式中，疼痛语义在早期 N400 阶段没有效应。",
        "counterevidence",
        "对“情绪/疼痛语义必然调节 N400”的宽泛说法构成直接反例；效应出现在后期 LPP。",
        "正/负目标词前呈现正性、一般负性或疼痛词启动，参与者判断目标词效价。",
        "样本量在当前锚点中未定位。",
        ["N400", "LPP"],
        "前/中/后 × 左/中/右 ROI。",
        "N400 早期窗；LPP 约400–700 ms。",
        "启动词效价/疼痛语义 × 目标词正负效价的一致/不一致比较。",
        "疼痛启动未改变 N400；疼痛启动后接正性目标时出现更大 LPP。",
        "疼痛是特定负性语义域；任务显式要求效价判断，且个体问卷与 ERP 差值无显著相关。",
        ["Q1", "Q2"],
    ),
    card(
        "PKL57JRG", 1,
        "We did not find an effect of reappraisal on the LPP or arousal ratings.",
        "在即时重评任务中，重评对 LPP 或唤醒度评分均无显著效应。",
        "counterevidence",
        "直接反驳“重评必然降低 LPP/唤醒”的无条件表述；后续新图片阶段才出现较小 LPP。",
        "先对一类负性图片重评、观看另一类负性及中性图片；随后被动观看各类新图片。",
        "n=41。",
        ["LPP"],
        "中央-顶区最大。",
        "约400 ms 起；论文分时段分析持续 LPP。",
        "重评类负性、仅观看类负性、中性；原图任务 vs 延迟的新图被动观看。",
        "即时任务中 LPP/唤醒度无重评效应；延迟阶段，相似新图片的 LPP 较小，但主观评分未泛化。",
        "神经指标与主观评分分离；类别泛化、延迟和无意图状态是效应出现的重要条件。",
        ["Q1", "Q3"],
    ),
    card(
        "54HS2AZY", 1,
        "The pleasant odor (lavender) attenuated LPP amplitudes for emotional pictures.",
        "薰衣草愉快气味降低了观看情绪图片时的 LPP 振幅。",
        "conditional_support",
        "支持跨感官的隐性情绪调节，但具体气味、图片效价与注意阶段限定明显。",
        "在中性、愉快、非愉快气味条件下评价正/负/中性图片的效价与唤醒度并记录 EEG。",
        "n=40。",
        ["N1", "EPN", "LPP"],
        "后部视觉情绪加工区域；精确电极需人工复核。",
        "早期 N1/EPN；晚期 LPP（精确窗需人工复核）。",
        "气味效价 × 图片效价；薰衣草/柑橘等愉快气味分别比较。",
        "愉快气味减弱负性图片的早期注意捕获；薰衣草减弱情绪图片 LPP，并伴随部分效价/唤醒评分变化。",
        "气味身份与愉快度未完全等价；跨感觉注意和熟悉度可能混淆，结果不能推广到语言 LPC。",
        ["Q1", "Q3"],
    ),
    card(
        "IRH47UG6", 1,
        "Future research [should focus] on simultaneous bilinguals, extended narratives ... and comparison of different modalities.",
        "综述建议未来聚焦同时双语者、连续叙事及跨模态比较。",
        "boundary",
        "指出现有双语情绪加工证据在群体、材料语境和模态上不足，限制跨语言泛化。",
        "PRISMA-P 系统综述健康双语者的情绪-语言神经影像、心理生理和认知研究。",
        "系统综述；纳入研究数量与总样本需人工复核。",
        ["ERP", "N400", "neuroimaging", "psychophysiology"],
        "跨研究。",
        "跨研究。",
        "L1/L2、单词/句子、不同熟练度/暴露度与模态。",
        "L2 情绪加工受熟练度、学习语境和暴露度影响，现有结果不支持简单的母语/二语二分。",
        "异质方法、去语境单词材料、同时双语者不足和模态不一致。",
        ["Q2", "Q3"],
    ),
    card(
        "JH5U3XYU", 1,
        "UT and LT elicited significantly more negative waveforms than MT in both primes.",
        "无关探测词和字面意义相关探测词比隐喻意义相关探测词诱发更负的 N400。",
        "conditional_support",
        "支持熟悉化与常规隐喻下的隐喻意义直接可及，但证据基于特定 300 ms 启动-探测范式。",
        "中文常规/熟悉化隐喻作启动，300 ms 后呈现隐喻相关、字面相关、无关或非词探测。",
        "n=28（14男；18–25岁，均为中文母语大学生）。",
        ["N400", "P600/late stage"],
        "预期中央-顶区 N400 与中央 P600；主要锚点为 N400。",
        "N400 约300–500 ms；晚期窗需人工复核。",
        "MT vs LT vs UT vs 非词，并比较常规与熟悉化隐喻启动。",
        "两类启动中 MT 均较 LT/UT 引出更小 N400，常规与熟悉化之间 MT/LT 无差异。",
        "启动-探测设计不等同自然句阅读；情绪未被操纵，结果只约束语义/熟悉度解释。",
        ["Q2"],
    ),
    card(
        "M256T5QC", 1,
        "English scientific metaphors elicited more negative N400s than Chinese ones at the parietal region.",
        "英语科学隐喻在顶区诱发的 N400 比中文科学隐喻更负。",
        "conditional_support",
        "直接显示语言优势与科学隐喻类型调节 N400/LPC，但不含情绪操纵。",
        "晚期不平衡双语者加工中文 L1 与英语 L2 的科学隐喻/字面表达。",
        "比较分析报告 n=17（F(1,16)）；完整招募与排除需人工复核。",
        ["N400", "LPC", "late negativity"],
        "顶区为核心；晚期效应扩展至额、中央、顶区并略偏右。",
        "N400 300–500 ms；LPC 550–800 ms。",
        "英语 L2 vs 中文 L1；科学隐喻与常规/字面表达。",
        "L2 科学隐喻 N400 更负、LPC 更不正，并出现范围不同的晚期负波。",
        "语言熟练度、科学知识和材料语言不可完全分离；作者使用 might/possible，机制解释仍为推断。",
        ["Q2", "Q3"],
    ),
]

BATCH_3 = [
    card(
        "KGUAISW6", 7,
        "The N400 ... might be related not only to metaphoric factor but also to scientific factor.",
        "该研究明确指出，N400 差异不仅可能来自隐喻性，也可能来自科学语境本身。",
        "boundary",
        "作者提出材料类别混淆，限制把 N400/LPC 差异单独归因于隐喻或语言。",
        "中英双语者阅读 L1/L2 科学隐喻与字面表达，比较 N400 和晚期成分。",
        "样本量未在当前证据锚点中定位。",
        ["N400", "LPC", "sustained late negativity"],
        "跨额、中央、顶区；晚期分布随语言变化。",
        "N400 约300–500 ms；晚期550–800 ms。",
        "中文/英语科学隐喻与对应字面条件。",
        "L2 条件显示更高的检索/整合负担，但科学语境与隐喻性可能共同驱动差异。",
        "与 M256T5QC 作者和主题高度重叠，可能存在样本/材料重用，合并前需核验。",
        ["Q2", "Q3"],
    ),
    card(
        "P9Y77QL6", 7,
        "The absolute difference in N400 amplitude ... novel metaphorical and ... nonsense phrases did not reach significance.",
        "新颖隐喻与无意义短语之间的 N400 绝对差异未达到显著。",
        "counterevidence",
        "限制把 N400 直接解释为成功的创造性整合；线性趋势不等于两条件显著差异。",
        "参与者按不寻常性与恰当性对两词短语分类，形成新颖隐喻、无意义和字面条件。",
        "样本量未在当前锚点中定位。",
        ["N400", "late component"],
        "中央-顶区为主要语义效应；精确 ROI 需人工复核。",
        "N400；后续晚期窗。",
        "新颖隐喻（高不寻常/高恰当）vs 无意义（高/低）vs 字面（低/高）。",
        "N400 随不寻常性呈梯度，但新颖隐喻与无意义的直接差异不显著；后期更关联恰当性。",
        "条件由参与者主观分类产生；创造性、恰当性和语义关联相互交织。",
        ["Q2", "Q3"],
    ),
    card(
        "F84Z4U84", 1,
        "ERP activity in this phase indexes appropriateness (nonsense > creative = common).",
        "500–900 ms 的晚期活动更像是在区分恰当性：无意义大于创意与常见用途。",
        "boundary",
        "晚期成分在此任务中索引恰当性而非单纯新颖或情绪，限制 LPC 的单一解释。",
        "改编用途任务：判断物体-用途组合的不寻常性与恰当性，形成无意义、创意和常见用途。",
        "样本量未在当前锚点中定位。",
        ["N400", "late component"],
        "精确 ROI 需人工复核。",
        "N400；探索性晚期窗500–900 ms。",
        "无意义 vs 创意 vs 常见用途。",
        "无意义和创意用途相较常见用途均有更大 N400；晚期活动主要区分恰当性。",
        "探索性晚期分析；判断任务与语言情绪范式不同，不能直接称为情绪 LPC。",
        ["Q2", "Q3"],
    ),
    card(
        "TMFE3UF6", 7,
        "Novel metaphors and nonsense phrases ... were not significantly distinguishable ... in the N400 time-window.",
        "新颖隐喻与无意义短语在 N400 时间窗内不可显著区分。",
        "counterevidence",
        "复现研究仍发现两类新颖材料的 N400 不可分，反对把 N400 当作成功隐喻整合的充分指标。",
        "以新颖隐喻诱发被动概念扩展，并比较字面、无意义短语及创造力个体差异。",
        "从 F(1,26) 推断分析样本 n=27；需人工核对招募/排除。",
        ["N400", "post-N400 late component"],
        "精确 ROI 需人工复核。",
        "N400；N400 后晚期成分。",
        "新颖隐喻 vs 无意义 vs 字面；创造力个体差异。",
        "N400 更反映原创性/不寻常性，晚期成分更关联恰当性；新颖隐喻与无意义的 N400 差异不显著。",
        "样本较小，个体差异分析功效有限；条件仍依赖主观分类。",
        ["Q2", "Q3"],
    ),
    card(
        "2CC2HQYF", 1,
        "Literal endings elicited the smallest N400, metaphors the largest N400.",
        "句末字面表达诱发最小 N400，隐喻诱发最大 N400。",
        "direct_support",
        "对隐喻性与 N400 振幅呈梯度关系的经典直接证据，但不含情绪操纵。",
        "18名成人阅读以字面、隐喻或中间字面映射结尾的句子。",
        "n=18 正常成人。",
        ["N400", "posterior positivity"],
        "N400 广泛/中央-顶；后部正波。",
        "N400 300–500 ms；后部晚期正波随后出现。",
        "字面 vs 字面映射 vs 隐喻句末词。",
        "N400 随隐喻性增加呈梯度；隐喻还诱发更大的后部正波。",
        "早期小样本；句末完形概率、语义关联与隐喻性可能共同影响 N400。",
        ["Q2"],
    ),
    card(
        "66IZGBKH", 7,
        "Identification of the N400 component was complicated by changes ... across the 300–500 ms interval.",
        "300–500 ms 内效应模式和头皮分布变化，使 N400 成分识别变得复杂。",
        "boundary",
        "论文直接警告固定宽窗可能把不同效应混在一起，适合用于时间窗边界审计。",
        "用语义判断比较常规隐喻、新颖隐喻、字面句和异常句。",
        "样本量未在当前锚点中定位。",
        ["early N400", "late N400", "P600/late positivity"],
        "头皮分布在300–500 ms内部变化。",
        "需拆分300–500 ms而非单一宽窗；另有晚期正成分。",
        "常规/新颖隐喻、字面与异常句。",
        "新颖隐喻与异常句在部分 N400 窗内同样大，常规隐喻更接近字面。",
        "成分识别受时间窗和拓扑变化影响；跨论文统一使用“N400 300–500 ms”会掩盖差异。",
        ["Q2", "Q3"],
    ),
    card(
        "W4SGNNVL", 3,
        "Incongruent contextual conditions evoked larger amplitudes of LPC than congruent ones.",
        "不一致语境比一致语境诱发更大的 LPC。",
        "conditional_support",
        "直接支持语境一致性调节晚期正成分，但效应只在特定科学隐喻类型上稳定。",
        "句末词范式，操纵图片语境一致性并比较两类科学隐喻、科学字面和无关表达。",
        "样本量未在当前锚点中定位。",
        ["N400", "LPC"],
        "多区域分析；精确电极需人工复核。",
        "N400 300–500 ms；LPC 晚期窗。",
        "一致 vs 不一致语境 × 科学隐喻类型/字面/无关表达。",
        "语境×类型交互显著；不一致语境增大 LPC，但300–500 ms的语境效应并非所有类型都显著。",
        "语境以图片呈现，类型交互强；不能将总体交互写成每一条件都有主效应。",
        ["Q2", "Q3"],
    ),
    card(
        "K2W6GBCV", 8,
        "No significant N400 difference [was observed] between conventional and novel similes.",
        "常规与新颖明喻之间没有显著 N400 差异。",
        "counterevidence",
        "说明常规性效应受比喻形式调节，不能从隐喻推广到明喻。",
        "中文隐喻与明喻理解任务，交叉操纵常规性。",
        "样本量未在当前锚点中定位。",
        ["N400", "P600/late positivity"],
        "N400 使用 FCz、Cz、CPz、Pz。",
        "N400 300–500 ms；晚期窗需人工复核。",
        "常规 vs 新颖 × 隐喻 vs 明喻。",
        "常规性改变隐喻的 N400，但没有改变明喻的 N400。",
        "熟悉度与常规性难完全分离；中文形式标记使隐喻/明喻任务要求不同。",
        ["Q2", "Q3"],
    ),
]

BATCH_4 = [
    card(
        "UH4G7YZA", 1,
        "The N400 effect was visible only in minimal context, whereas the P600 was visible ... with contextual cues.",
        "N400 只在最小语境中出现，而 P600 在有无支持语境时都可见。",
        "boundary",
        "直接证明语境可消除隐喻 N400，却不一定消除 P600，两个成分不能视为同一机制的早晚版本。",
        "实验1最小语境、实验2显式提供隐喻本体与喻体共同点的支持语境，比较隐喻和字面表达。",
        "样本量未在当前锚点中定位。",
        ["N400", "P600"],
        "典型中央-顶 N400/P600；精确电极需人工复核。",
        "N400 约300–500 ms；P600 为后续晚期窗。",
        "隐喻 vs 字面 × 最小语境 vs 支持语境。",
        "支持语境消除了 N400，但 P600 仍存在，提示前者偏语境预期/词汇通达，后者偏语用重构。",
        "两实验而非完全同一被试内语境操纵；语境支持方式较显式。",
        ["Q2", "Q3"],
    ),
    card(
        "KMNAMCKJ", 1,
        "A centroparietal N400 (300–450 ms) ... [was] greater for metaphors.",
        "隐喻在中央-顶区诱发更大的 300–450 ms N400。",
        "conditional_support",
        "直接比较常规隐喻、反讽和字面陈述，但部分晚期差异仅为统计/视觉趋势。",
        "序列陈述 ERP 范式比较常规隐喻、反讽和字面语言，并以 eLORETA 探索源定位。",
        "n=30，均右利手，21–34岁。",
        ["N400", "Late N400/N500", "LANSW", "eLORETA"],
        "N400中央-顶；晚期 N400 右侧占优；LANSW左额。",
        "N400 300–450 ms；Late N400 450–600 ms；LANSW 450–1000 ms。",
        "常规隐喻 vs 反讽 vs 字面陈述。",
        "隐喻显示更大 N400、晚期 N400趋势与显著左额慢负波；晚期不一定表现为正波。",
        "部分结果仅趋势；eLORETA为空间估计，不能消除词汇关联性、效价和记忆过程混淆。",
        ["Q2", "Q3"],
    ),
    card(
        "B5F5XG3T", 7,
        "RMET scores [modulated] the N400 ... but [showed] no interaction ... with Metaphor Type.",
        "情绪识别能力与两类隐喻的 N400 总体相关，但未与隐喻类型发生交互。",
        "boundary",
        "个体差异影响 N400，但不能据此断言心理/情绪型隐喻受到特异调节。",
        "比较物理属性与心理属性隐喻，并以眼神读心测验和动画任务测量心智理论。",
        "样本量未在当前锚点中定位。",
        ["N400", "sustained negativity", "GAMM"],
        "300–500 ms 拓扑与 N400 相符；晚期500–800 ms持续负波。",
        "300–500 ms；500–800 ms。",
        "物理隐喻 vs 心理隐喻；RMET/动画任务连续预测。",
        "物理隐喻负波更大且持续；RMET 越高总体 N400 越小，但未特异作用于心理隐喻。",
        "RMET 同时涉及词汇/情绪识别；相关个体差异不是因果操纵。",
        ["Q2", "Q3"],
    ),
    card(
        "SIQQH3LP", 1,
        "Novel metaphors produced larger amplitudes over the LH ... than conventional metaphors.",
        "新颖隐喻相较常规隐喻在左半球产生更大振幅。",
        "conditional_support",
        "常规性与注意网络共同影响 N400，但结果来自显式新颖度评价任务。",
        "隐喻新颖度评价任务同步记录 ERP，并用注意网络测验测量警觉、定向和执行控制。",
        "样本量未在当前锚点中定位。",
        ["N400", "attention networks"],
        "左半球差异突出；精确电极 ROI 需人工复核。",
        "常规隐喻 N400 峰更早；主要分析窗需人工复核。",
        "新颖 vs 常规隐喻；三类注意网络与 N400 的相关。",
        "新颖隐喻评分更慢、N400 峰更晚且左半球振幅更大；只与执行控制网络相关。",
        "显式评价会把注意引向新颖性；注意关联为相关关系，不证明执行控制造成 N400 差异。",
        ["Q2", "Q3"],
    ),
    card(
        "2YE6KRW9", 1,
        "Metaphor familiarity modulated N400 of both groups ... [but] P600 [only] of low executive control.",
        "隐喻熟悉度调节两组的 N400，但只调节低执行控制组的 P600。",
        "conditional_support",
        "直接显示个体执行控制对晚期成分的影响不同于 N400，支持有条件的分阶段解释。",
        "L2 语义启动/判断任务比较高熟悉隐喻、低熟悉隐喻和字面词对；Stroop 区分执行控制组。",
        "样本量未在当前锚点中定位。",
        ["N400", "P600", "sLORETA"],
        "额、中央、顶区；低熟悉隐喻时右额上/中回源活动更强。",
        "N400 300–500 ms；P600 晚期窗。",
        "高/低熟悉隐喻 vs 字面 × 高/低执行控制。",
        "低执行控制组总体 N400/P600 更负；熟悉度影响两组 N400，但仅影响低控制组 P600。",
        "组别来自 Stroop 分组且为 L2 样本；熟悉度、语言水平和执行控制可能相关。",
        ["Q2", "Q3"],
    ),
    card(
        "3CV763RE", 1,
        "With masked priming, the N400-difference was reduced for metaphors and vanished for metonymies.",
        "字面意义掩蔽启动后，隐喻的 N400 差异减小，转喻的差异消失。",
        "boundary",
        "说明无意识启动和修辞类型改变 N400，限制把成分差异当作刺激固有属性。",
        "跨模态掩蔽启动 ERP；隐喻与转喻分别在有/无字面意义相关启动下呈现。",
        "样本量未在当前锚点中定位。",
        ["N400", "Late Positivity"],
        "精确 ROI 需人工复核。",
        "N400 约250–500 ms；Late Positivity 约1100–1300 ms。",
        "隐喻/转喻 vs 字面；相关掩蔽启动 vs 无启动。",
        "无启动时隐喻呈 N400-晚期正波双相模式；字面相关掩蔽启动减小 N400 差异。",
        "极晚正波的定义不同于常见 LPC 窗；掩蔽有效性与跨模态启动是特定条件。",
        ["Q2", "Q3"],
    ),
    card(
        "GG4GWWBS", 1,
        "Late Positive Components revealed no significant difference between metaphors and literal sentences.",
        "隐喻与字面句在 600–1400 ms 晚期正成分上没有显著差异。",
        "counterevidence",
        "对“隐喻加工普遍伴随晚期正波”的说法构成直接反证。",
        "四个实验比较熟悉/不熟悉隐喻与字面句，并操纵前置语境相关性。",
        "至少一个分析显示误差自由度11（推测 n=12）；各实验样本需人工复核。",
        ["N400", "Late Positive Components"],
        "精确 ROI 需人工复核。",
        "N400 约300–600 ms；LPC 600–1000与1000–1400 ms。",
        "熟悉/不熟悉隐喻 vs 字面；相关/无关前置语境。",
        "隐喻句末词 N400 更大，但两个晚期窗都无显著隐喻-字面差异；语境效应早至约300 ms。",
        "早期研究样本小；材料与成分分析标准不同于现代研究。",
        ["Q2", "Q3"],
    ),
    card(
        "FMGCRBPQ", 1,
        "Met verbs evoked a significantly larger N400 response at frontal brain region compared to Abs verbs.",
        "动作隐喻动词相较抽象动词在额区诱发更大的 N400。",
        "conditional_support",
        "支持隐喻的具体/动作语义调节 N400，但不涉及情绪效价或唤醒度。",
        "比较中文动作动词在隐喻、字面和抽象语境中的加工，以检验具体性/具身效应。",
        "最终样本量未定位；文中报告因伪迹额外排除2人。",
        ["N400"],
        "额区：隐喻-抽象；后区：隐喻-字面对比。",
        "额区200–500 ms；后区300–500 ms。",
        "隐喻动作动词 vs 字面动作动词 vs 抽象动词。",
        "不同对比产生不同头皮分布和时间范围的 N400，提示具体行动语义参与。",
        "作者明确指出结果不等同支持“字面优先”；具身/具体性与语义关联仍可能混淆。",
        ["Q2"],
    ),
]

NO_PDF = [
    card(
        "PML39LCM", None, "",
        "本地 Zotero 条目没有 PDF，无法核验情绪语境对情绪词 ERP 的原文结果与页码。",
        "insufficient",
        "只有元数据/摘要线索，禁止写成已证实。",
        "据摘要：比较中性、正性、负性一致语篇中的情绪词加工。",
        "未定位。", ["ERP"], "未定位。", "未定位。",
        "正/负/中性情绪语境与情绪词。",
        "未核验。", "缺少本地 PDF；需补附件或人工提供全文。", ["Q2", "Q3"],
    ),
    card(
        "CNMC6QPE", None, "",
        "本地 Zotero 条目没有 PDF，无法核验可预测/不可预测语境中不同效价情绪词的 ERP 结果。",
        "insufficient",
        "摘要指向直接相关问题，但无页码原文，不具备证据资格。",
        "据摘要：情绪词阅读，操纵语境可预测性和效价。",
        "未定位。", ["ERP"], "未定位。", "未定位。",
        "可预测 vs 不可预测 × 不同效价情绪词。",
        "未核验。", "缺少本地 PDF；条目标题含投稿编号痕迹，需核对正式发表信息。", ["Q2", "Q3"],
    ),
    card(
        "ACJAJ7ZB", None, "",
        "本地 Zotero 条目没有 PDF，无法核验重音如何影响口语情绪词 ERP。",
        "insufficient",
        "听觉/韵律边界高度相关，但没有可定位原文。",
        "据标题：重音操纵下的口语情绪词 ERP。",
        "未定位。", ["ERP"], "未定位。", "未定位。",
        "重音 × 情绪词条件。",
        "未核验。", "缺少本地 PDF；需确认语言、任务和声学控制。", ["Q1", "Q2"],
    ),
    card(
        "MTRD2WDW", None, "",
        "本地 Zotero 条目没有 PDF，无法核验面孔、emoji 与词语情绪违背的 N400 结果。",
        "insufficient",
        "可能提供跨模态反证/边界，但无原文页码。",
        "据标题：跨面孔、emoji、词语的情绪违背 N400。",
        "未定位。", ["N400"], "未定位。", "未定位。",
        "跨模态情绪一致/违背。",
        "未核验。", "缺少本地 PDF；需确认是否同一任务和同一被试内比较。", ["Q2", "Q3"],
    ),
    card(
        "FETEEPSJ", None, "",
        "本地 Zotero 条目没有 PDF，无法核验状态焦虑对意外语义刺激 N400 的影响。",
        "insufficient",
        "可作为个体/状态变量边界候选，但当前只有题名。",
        "据标题：状态焦虑 × 意外语义刺激的 N400。",
        "未定位。", ["N400"], "未定位。", "未定位。",
        "高/低状态焦虑或连续焦虑 × 预期/意外语义。",
        "未核验。", "缺少本地 PDF；需确认焦虑分组、任务、语言和统计模型。", ["Q2", "Q3"],
    ),
]


def main():
    state = {r["zotero_item_key"]: r for r in json.loads((WORK / "selection_state.json").read_text(encoding="utf-8"))}
    cards = []
    all_cards = BATCH_1 + BATCH_2 + BATCH_3 + BATCH_4 + NO_PDF
    for index, item in enumerate(all_cards, start=1):
        meta = state[item["zotero_item_key"]]
        item = {
            "evidence_id": f"NT-E{index:03d}",
            "title": meta.get("title"),
            "bibtex_key": meta.get("bibtex_key"),
            "attachment_key": meta.get("attachment_key"),
            **item,
        }
        cards.append(item)
    payload = {
        "schema_version": "1.0",
        "generated_date": "2026-09-28",
        "page_definition": "1-based PDF page number from the local attachment; not the printed journal page label",
        "allowed_evidence_roles": ["direct_support", "conditional_support", "boundary", "counterevidence", "insufficient"],
        "cards": cards,
    }
    (ROOT / "evidence_cards.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"cards": len(cards), "batch_1": len(BATCH_1), "batch_2": len(BATCH_2), "batch_3": len(BATCH_3), "batch_4": len(BATCH_4), "missing_pdf": len(NO_PDF)}, ensure_ascii=False))


if __name__ == "__main__":
    main()

